# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Corinne Jones
tagline:          'Home'
description:      '<a href="mailto:corinne.jones@epfl.ch">corinne.jones@epfl.ch</a>  <br /> <a href="https://github.com/cjones6" target="_blank"> https://github.com/cjones6 </a>'
url:              http://cjones6.github.io
baseurl:          /

author:
  name:           'Corinne Jones'

paginate:         5

# Custom vars
version:          1.0
plugins: [jekyll-paginate]

github:
  repo:           https://github.com/cjones6

