# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Corinne Jones
tagline:          'Home'
description:      '<a href="mailto:cjones6@uw.edu">cjones6@uw.edu</a>  <br /> <a href="https://github.com/cjones6" target="_blank"> https://github.com/cjones6 </a>'
url:              http://www.stat.washington.edu/~cjones6
baseurl:          /~cjones6/

author:
  name:           'Corinne Jones'

paginate:         5

# Custom vars
version:          1.0
plugins: [jekyll-paginate]

github:
  repo:           https://github.com/cjones6

